name: Docker Image

on:
  push:
    branches: main

env:
  platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/s390x,linux/ppc64le,linux/riscv64
  repoName: ${{ github.event.repository.name }}

jobs:
  building:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set imageName based on the repository name
        id: step_one
        run: |
          imageName="${{github.repository}}"
          echo $imageName
          echo "Repository name is ${GITHUB_REPOSITORY}"
          echo "Name ${{ github.event.repository.name }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v3
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       we2app/${{ github.event.repository.name }}:latest
      #       we2app/${{ github.event.repository.name }}:1.0.0
